spring:
  datasource:
    url: jdbc:h2:mem:orders
    driverClassName: org.h2.Driver
    username: sa
    password:
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
